const user_found = '0AE0 : User found!'
const password_matched = '0AE1 : Password matched!'
const logged_in = '0AE2 : Logged in!'
const dir_found = '0AE3 : Requested directory found!'
const dir_changed = '0AE4 : Current working directory changed!'
const file_found = '0AE5 : Requested file was found!'
const file_exists = '0AE6 : File already exists!'
const dir_made = '0AE7 : The directory was successfully made!'
